name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Merge Conflict
        run: git merge-base --is-ancestor ${{ github.base_ref }} ${{ github.head_ref }}
        id: check_merge_conflict
        continue-on-error: true

      - name: Check Modified Files
        run: |
          if [[ $(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }}) == "README.md" ]]; then
            echo "Only the README file is modified. No merge conflict detected."
          else
            echo "Files other than README.md are modified. Skipping auto-merge."
            exit 1
          fi

      - name: Auto Merge
        if: steps.check_merge_conflict.outcome == 'success'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge --no-ff ${{ github.head_ref }} -m "Auto merge pull request"
          git push origin ${{ github.base_ref }}
